dependencies:
- smartcontractkit/chainlink@1.1.1
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink@1.1.1'

dotenv: .env
networks:
  default: development
  rinkby:
    eth_usd_price_feed: 0x8A753747A1FA494EC906CE90E9F37563A8AF630E
wallets:
  from_key: ${PRIVATE_KEY}

